# 使用官方提供的基础镜像
FROM alpine:latest

# 设置工作目录
WORKDIR /app

# 将压缩包复制到容器中
COPY v3.3.7/tfcenter-linux-arm-v3.3.7.tar.gz /app/

# 解压压缩包
RUN tar -xzvf tfcenter-linux-arm-v3.3.7.tar.gz

RUN mv tfcenter/tfcenter32 tfcenter/tfcenter

# 可选：清理工作目录，减少镜像大小
RUN rm tfcenter-linux-arm-v3.3.7.tar.gz

RUN rm tfcenter/tfcenter64

RUN rm tfcenter/tfcenter-daemon32

RUN rm tfcenter/tfcenter-daemon64


# 定义容器启动时执行的命令
CMD ["bash"]
